# Generated by Django 4.0.2 on 2022-05-07 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='professeur',
            field=models.IntegerField(null=True),
        ),
    ]
