# Generated by Django 4.0.2 on 2022-05-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('element', '0002_alter_element_professeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='heures',
            field=models.FloatField(default=0.0, max_length=50),
        ),
        migrations.AlterField(
            model_name='element',
            name='pourcentage_element',
            field=models.FloatField(blank=True, max_length=50),
        ),
    ]
