# Generated by Django 4.0.2 on 2022-05-06 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='filliere',
            new_name='filiere',
        ),
    ]
