# Generated by Django 4.0.2 on 2022-05-06 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anneeUniversitaire', '0001_initial'),
        ('filliere', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etudiant', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anneeUniversitaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anneeUniversitaire_inscription', to='anneeUniversitaire.anneeuniversitaire')),
                ('filiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filiere_inscription', to='filliere.filiere')),
            ],
        ),
    ]
