# Generated by Django 4.0.2 on 2022-05-06 21:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('creneau', '0001_initial'),
        ('element', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('type', models.CharField(max_length=255)),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Creneau_Seance', to='creneau.creneau')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Element_Seance', to='element.element')),
            ],
        ),
    ]
